name: ci

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v
