name: on main push

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/wf-build.yml

  build-container:
    uses: ./.github/workflows/wf-build-container.yml
